services:

  postgres:
    image: postgres:16
    container_name: iot-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: iot_platform

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

    networks:
      - iot-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: iot-pgadmin
    restart: unless-stopped

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: changeme

    ports:
      - "5050:80"

    depends_on:
      - postgres

    volumes:
      - pgadmin-data:/var/lib/pgadmin

    networks:
      - iot-network

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: iot-mosquitto
    restart: unless-stopped

    ports:
      - "1883:1883"
      - "8883:8883"
      - "9001:9001"

    volumes:
      - ./docker/mosquitto/config:/mosquitto/config
      - ./docker/mosquitto/data:/mosquitto/data
      - ./docker/mosquitto/log:/mosquitto/log
      - ./docker/mosquitto/certs:/mosquitto/certs

    networks:
      - iot-network

  backend:
    build:
      context: ./backend

    container_name: iot-backend

    restart: unless-stopped

    depends_on:
      - postgres
      - mosquitto

    ports:
      - "8000:8000"

    volumes:
      - ./backend/certs:/app/backend/certs

    environment:
      - SSL_CERTFILE=/app/backend/certs/cert.pem
      - SSL_KEYFILE=/app/backend/certs/key.pem

    networks:
      - iot-network
  frontend:
    build:
      context: ./frontend

    container_name: iot-frontend

    restart: unless-stopped

    depends_on:
      - backend

    environment:
      VITE_API_URL: https://localhost:8000

    ports:
      - "5173:5173"

    volumes:
      - ./frontend:/app
      - /app/node_modules

    networks:
      - iot-network

volumes:
  pgdata:
  pgadmin-data:

networks:
  iot-network:
    driver: bridge