apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: iot-platform
type: Opaque
stringData:
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: changeme
  POSTGRES_DB: iot_platform
---
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: iot-platform
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: admin@example.com
  PGADMIN_DEFAULT_PASSWORD: changeme
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: iot-platform
data:
  VITE_API_URL: "http://localhost:8000"
