apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: iot-platform
data:
  MQTT_HOST: mosquitto
  MQTT_PORT: "1883"
  ALGORITHM: HS256
  ACCESS_TOKEN_EXPIRE_MINUTES: "60"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: iot-platform
data:
  VITE_API_URL: "http://localhost:8000"
